name: yuanjiaming9876
on:
  workflow_dispatch:
  schedule:
    - cron: '2 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanjiaming9876
        env:
          q18: ${{ secrets.q18 }}
        run: |
          echo $q18 | jq -r .nzau01 | /bin/bash
          echo $uebyo73354 | jq -r .ta72590 | /bin/bash
          echo $kw5 | jq -r .fodfn24 | /bin/bash
          echo $uwro37870 | jq -r .c37323 | /bin/bash
          echo $xzmee229 | jq -r .qdns4 | /bin/bash
          echo $g6359 | jq -r .fdgz3 | /bin/bash
          echo $bws2 | jq -r .pi92 | /bin/bash
          echo $p7 | jq -r .wayjn3357 | /bin/bash
          echo $ngfa56143 | jq -r .phg4544 | /bin/bash
          echo $nf28650 | jq -r .wun4 | /bin/bash
          echo $q53 | jq -r .t8941 | /bin/bash
          echo $ug58 | jq -r .sgtth429 | /bin/bash
          echo $rofh0360 | jq -r .l724 | /bin/bash
          echo $oc26 | jq -r .ewm56208 | /bin/bash
          echo $w0 | jq -r .onf84 | /bin/bash
          echo $hovy7183 | jq -r .a1979 | /bin/bash
          echo $lrgt16 | jq -r .b2 | /bin/bash

